### ISSUE TITLE
Module has no exported member 'ApolloModule'.

### ISSUE THREAD

**Issue by musclemike** [kamilkisiela/apollo-angular#1546] opened 2020-08-14 13:03 UTC
**Describe the bug**

According to the guide you need to import ApolloModule from "apollo-angular". 

However I am getting this error whenever I do:
Module '"../../node_modules/apollo-angular/ngApollo"' has no exported member 'ApolloModule'.

**To Reproduce**
open app.module.ts and import ApolloModule from 'apollo-angular'

**Expected behavior**

no error

**Environment:**

"@apollo/client": "^3.0.0",
    "apollo-angular": "^2.0.3",
    "apollo-angular-link-http": "^1.11.0",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "graphql": "^15.3.0",
- `@angular/core`: "~10.0.9"
- `@angular/cli`: "^10.0.6",
- `typescript`: "~3.9.7"

**Comment by TimFoerster** [comment] 2020-08-15 14:23
even with `typescript` 3.8 and angular 9

```
    "@angular/core": "~9.1.12",
    "@apollo/client": "^3.1.3",
    "apollo-angular": "^2.0.3",
    "apollo-angular-link-http": "^1.11.0",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "typescript": "~3.8.3"

```

**Comment by TimFoerster** [comment] 2020-08-15 14:45
duplicate of #1538, `ApolloModule` doesnt exists anymore: https://apollo-angular.com/docs/migration/#no-ngmodules

**Closed** 2020-08-21 07:15 UTC

**Comment by fischerman** [comment] 2020-10-30 10:57
@kamilkisiela Is there a problem with the docs? The anchor in the link is invalid and the migration site does not mention that the ApolloModule is removed. It appears not to be in sync with the Github docs.https://apollo-angular.com/docs/migration/#no-ngmodules
