### ISSUE TITLE
Angular 15

### ISSUE THREAD

**Issue by Destreyf** [kamilkisiela/apollo-angular#1847] opened 2022-11-18 14:26 UTC
**Describe the bug**
Currently cannot install apollo-angular inside of an angular 15 repository.

**Additional context**
I recently upgraded my repository to angular 15 and cannot install apollo-angular due to dependency conflict.

**Comment by kpkingg** [comment] 2022-11-19 23:44
Hello
Me too cannot install apollo-angular v.4.1.1 ( I'm using angular v15.0.0 / node v18.12.1 / npm v8.19.2), apparently is not compatible with angular v15 yet.

rm__v2 % ng add apollo-angular
ℹ Using package manager: npm
⚠ Unable to find compatible package. Using 'latest' tag.
⚠ Package has unmet peer dependencies. Adding the package may not succeed.

The package [apollo-angular@4.1.1](mailto:apollo-angular@4.1.1) will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: rm--v2@0.0.0
npm ERR! Found: @angular/core@15.0.0
npm ERR! node_modules/@angular/core
npm ERR! @angular/core@"^15.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^14.0.0" from [apollo-angular@4.1.1](mailto:apollo-angular@4.1.1)
npm ERR! node_modules/apollo-angular
npm ERR! apollo-angular@"4.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/.npm/_logs/2022-11-19T15_09_05_281Z-debug-0.log
✖ Packages installation failed, see above.

**Closed** 2022-11-20 15:46 UTC

**Comment by danielzgtg** [comment] 2022-11-22 14:27
The workaround before it is published is to add the following to `package.json`:

```
  },
  "overrides": {
    "apollo-angular": {
      "@angular/core": "^15.0.0"
    }
  }
```

**Comment by bendehghan** [comment] 2022-12-02 23:31
Is anything else holding back publishing this? I would keep the bug open until the publish. That way external people can track it easier. 
Thanks, Ben

**Comment by PowerKiKi** [comment] 2022-12-03 17:48
The issue is closed automatically when the related PR is merged.

If you need to know whether a certain fix is released either check change log, or better yet check the individual commit to see if it is included in any tag at all.

Nothing is really holding back the release. But only @kamilkisiela can do it. And I guess he's been busy lately

**Comment by TomONeill** [comment] 2022-12-12 11:09
@PowerKiKi Thanks for the update.

@kamilkisiela can you push a new release to npm?

**Comment by marcos-castrillo** [comment] 2022-12-22 15:36
Thank you for the PR, my team would also like to see it published

**Comment by SimonCockx** [comment] 2022-12-27 22:34
We would also love this to be published (@kamilkisiela) . Thanks @PowerKiKi for the PR!

**Comment by bendehghan** [comment] 2023-01-04 19:20
Does anyone have an example of using apollo with typescript in an angular project without this package? We're not using any local caching so I think it'd be just safer to go with the typescript directly. I'm looking online bug google keeps pointing to this package when searching for apollo + typescript + angular. I'm looking to remove our dependency on this package since it seems dormant. Thank you and happy new year :)

**Comment by PowerKiKi** [comment] 2023-01-05 01:07
"local caching" has nothing to do with Apollo Angular, it comes with Apollo core. Apollo Angular only offer a wrapper for easier use within an Angular project, but it adds no (major) features.

Also Apollo Angular is far from dormant. We are experiencing a small delay in releasing right now, but otherwise the project is alive and kept in sync with both Apollo and Angular regularly. The overall activity is not huge, because precisely this package is "only" a wrapper.

**Comment by bbroereES** [comment] 2023-01-18 09:14
We would love to see this published too!

**Comment by PowerKiKi** [comment] 2023-01-18 09:48
It was released as https://www.npmjs.com/package/apollo-angular/v/4.2.0
