### ISSUE TITLE
Update with "ng update apollo-angular" is failing for 3.0.0

### ISSUE THREAD

**Issue by mbuening** [kamilkisiela/apollo-angular#1761] opened 2022-02-23 11:37 UTC
**Describe the bug**

Update to `3.0.0` with `ng update apollo-angular` is failing for a project that was using `2.6.0`.

**To Reproduce**

Run `ng update apollo-angular` for a project that was using `2.6.0`.

**Expected behavior**

I expect the package to be installed and for the project to be updated according to the schematic logic.

**Environment:**

```
- @angular/cli@13.2.4 
- @angular/core@13.2.3 
- @apollo/client@3.5.8 
- apollo-angular@2.6.0 
- graphql@15.8.0 
- typescript@4.4.4 
```

**Additional context**

[error] Error: Cannot find module '\<path_hidden\>/node_modules/apollo-angular/schematics/migrations/v2'
Require stack:
- \<path_hidden\>/node_modules/@angular/cli/models/schematic-engine-host.js
- \<path_hidden\>/node_modules/@angular/cli/commands/update-impl.js
- \<path_hidden\>/node_modules/@angular-devkit/schematics/tools/export-ref.js
- \<path_hidden\>/node_modules/@angular-devkit/schematics/tools/index.js
- \<path_hidden\>/node_modules/@angular/cli/utilities/json-schema.js
- \<path_hidden\>/node_modules/@angular/cli/models/command-runner.js
- \<path_hidden\>/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at SchematicEngineHost._resolveReferenceString (\<path_hidden\>/node_modules/@angular/cli/models/schematic-engine-host.js:57:39)
    at SchematicEngineHost.createSchematicDescription (\<path_hidden\>/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:181:34)
    at SchematicEngine.createSchematic (\<path_hidden\>/node_modules/@angular-devkit/schematics/src/engine/engine.js:228:38)
    at UpdateCommand.executeMigrations (\<path_hidden\>/node_modules/@angular/cli/commands/update-impl.js:168:52)
    at UpdateCommand.run (\<path_hidden\>/node_modules/@angular/cli/commands/update-impl.js:589:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UpdateCommand.validateAndRun (\<path_hidden\>/node_modules/@angular/cli/models/command.js:136:22)

**Comment by MikaStark** [comment] 2022-03-01 14:18
Duplicate of https://github.com/kamilkisiela/apollo-angular/issues/1760

**Closed** 2022-04-05 13:29 UTC
