### ISSUE TITLE
View Engine is now legacy on Angular 13

### ISSUE THREAD

**Issue by rafagsiqueira** [kamilkisiela/apollo-angular#1752] opened 2022-02-08 01:26 UTC
Getting this "warning" when compiling on Angular 13:

```- Compiling with Angular sources in Ivy full compilation mode.
Processing legacy "View Engine" libraries:
- apollo-angular [es2015/esm2015] (https://github.com/kamilkisiela/apollo-angular)
- apollo-angular/http [es2015/esm2015] (https://github.com/kamilkisiela/apollo-angular)
Encourage the library authors to publish an Ivy distribution.
```
So this is my encouragement! :-D

**Comment by DaSchTour** [comment] 2022-02-10 14:27
MR already available: #1729
Duplicate of: #1732

**Closed** 2022-02-17 10:39 UTC
