### ISSUE TITLE
Installation fails: cannot find @angular\cli\src\command-builder\utilities\schematic-engine-host.js

### ISSUE THREAD

**Issue by jastraberg** [kamilkisiela/apollo-angular#1872] opened 2022-12-27 17:48 UTC
**Describe the bug**

Installation fails with 

```
PS C:\Users\user\Desktop\myproject> ng add apollo-angular
Node.js version v19.3.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
ℹ Using package manager: npm
⚠ Unable to find compatible package. Using 'latest' tag.
⚠ Package has unmet peer dependencies. Adding the package may not succeed.

The package apollo-angular@4.1.1 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Cannot find module 'C:\Users\user\Desktop\myproject\node_modules\apollo-angular\schematics\install\index'
Require stack:
- C:\Users\user\Desktop\myproject\node_modules\@angular\cli\src\command-builder\utilities\schematic-engine-host.js
PS C:\Users\user\Desktop\myproject> 
```

**To Reproduce**
`npm i apollo-angular`

**Expected behavior**

Should install without errors.

**Environment:**

```
- @angular/cli@15.0.3
- @angular/core@15.0.3
- apollo-angular@4.1.1
- typescript@4.8.4
```

**Additional context**

N/A

**Comment by PowerKiKi** [comment] 2022-12-28 07:06
Duplicate of #1848

**Closed by PowerKiKi** 2022-12-28 07:06 UTC
