### ISSUE TITLE
ng add apollo-angular does not seem to install correctly

### ISSUE THREAD

**Issue by ardianmaliqaj-git** [kamilkisiela/apollo-angular#1764] opened 2022-02-26 01:02 UTC
I'm getting this error message when I try to "ng add apollo-angular" after installing it. Not sure where the problem is exactly, if I missed something and got anything wrong: 

An unhandled exception occurred: Cannot find module '\node_modules\apollo-angular\schematics\install'
Require stack:
- \node_modules\@angular\cli\models\schematic-engine-host.js
- \node_modules\@angular\cli\models\schematic-command.js
- \node_modules\@angular\cli\commands\add-impl.js
- \node_modules\@angular-devkit\schematics\tools\export-ref.js
- \node_modules\@angular-devkit\schematics\tools\index.js
- \node_modules\@angular\cli\utilities\json-schema.js
- \node_modules\@angular\cli\models\command-runner.js
- \node_modules\@angular\cli\lib\cli\index.js
- \AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js

**Comment by weeken88** [comment] 2022-02-26 13:32
We are also getting the same error (Angular 12 & 13). Still waiting for an update.

**Comment by MikaStark** [comment] 2022-03-01 14:18
Duplicate of https://github.com/kamilkisiela/apollo-angular/issues/1760

**Closed** 2022-04-05 13:30 UTC
