### ISSUE TITLE
Compatibility with Angular 15

### ISSUE THREAD

**Issue by CharlieGreenman** [kamilkisiela/apollo-angular#1864] opened 2022-12-18 10:10 UTC
Currently errors out

```
 Found: @angular/core@15.0.4
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"15.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^14.0.0" from apollo-angular@4.1.1
npm ERR! node_modules/apollo-angular
npm ERR!   apollo-angular@"^4.1.1" from the root project
```

**Comment by PowerKiKi** [comment] 2022-12-18 14:15
Duplicate of #1847

**Comment by CharlieGreenman** [comment] 2022-12-18 14:16
sorry missed that

**Closed by PowerKiKi** 2022-12-18 14:15 UTC
