### ISSUE TITLE
watchQuery does not trigger on mutation

### ISSUE THREAD

**Issue by Nielsien** [kamilkisiela/apollo-angular#1668] opened 2021-05-18 15:46 UTC
**Describe the bug**

I was testing the watchQuery valuechanges but it does not seem to trigger on a mutation on the correct object.
I can fetch the first data with the subscriber but after that I dont get any updates

**To Reproduce**

I initialize the following subscriber in the constructor

```
const query = gql`
query Query($getWithIdId: String!) {
  getWithID(id: $getWithIdId) {
	  firstName
	  id
  }
}`;

this.apollo
  .watchQuery<any>({
    query,
    variables: { getWithIdId: "ID" },
    // fetchPolicy: "network-only"
  }).valueChanges.subscribe(({ data, loading }) => {
    // ONLY COMES HERE ONES, (on init)
    console.log(data, loading);
    this.data = data;
  });
```

But after mutating/ updating the query it does not trigger the valueChange, mutating from the frontend also does not seem to work.

Switching the fetchPolicy also does not seem to do a lot

**Expected behavior**

I would like an update in the watchQuery subscriber after a mutate of the query

**Environment:**

```
- @angular/cli@11.2.7
- @angular/core@11.2.8
- @apollo/client@^3.3.18
- apollo-angular@^2.4.0
- graphql@^15.5.0
- typescript@~4.0.2
- rxjs:@^7.0.1
```

**Additional context**
I am using the new rxjs, maybe it is because of this?

**Comment by kamilkisiela** [comment] 2021-05-24 12:41
Can you show your query as well? The issue is not related to Apollo Angular but probably Apollo Client itself. New results are emitted from Cache to the watchQuery, Apollo Angular is just a transport layer.

**Comment by florent1933** [comment] 2021-05-31 13:38
Thanks @Nielsien for opening the issue, I have the same problem.

@kamilkisiela, MRE => https://stackblitz.com/edit/angular-ivy-swamnt?file=src/app/app.component.ts

In the MRE, we can see that the cache is updated (with apollo dev-tools) but it doesn't trigger the update on the watchQuery.

As you said, maybe it's not related to apollo-angular itself but I didn't find a corresponding issue on the apollo-client repo.

**Comment by josnin** [comment] 2021-06-08 13:11
I noticed that if you do add new record (mutation) it will not force to update the cache, hence will not trigger the watchQuery
not sure if its expected, normally i use to call refetchQueries or call.evict (after upgrade to Apollo 3)  to do force update

if you only modify a record (mutation) it can update the cache, and was able to trigger the watchQuery

**Comment by kamilkisiela** [comment] 2021-06-08 13:29
Closing since it's ApolloClient related, not Apollo Angular. Please open an issue there.

**Closed by kamilkisiela** 2021-06-08 13:29 UTC
